"""Build the site's body font, DJM Text, from the vendored Libron release.

Subsets Libron to Latin + Latin Extended-A (enough for English and Serbian
Latin) and renames the family. Libron is a Reserved Font Name under the OFL,
so a modified version must ship under a different name.

Requires fonttools and brotli:  pip install fonttools brotli
Run with:                       npm run fonts
"""

from __future__ import annotations

import shutil
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "fonts" / "libron-0.30"
OUT = ROOT / "public" / "fonts" / "djm-text-0.30"

FAMILY = "DJM Text"
PS_FAMILY = "DJMText"
STYLES = ("Regular", "Bold")

UNICODES = (
    "U+0020-007E,"  # Basic Latin
    "U+00A0-00FF,"  # Latin-1 Supplement
    "U+0100-017F,"  # Latin Extended-A (č ć đ š ž)
    "U+2010-2027,U+2030-203A,"  # dashes, quotes, ellipsis, primes
    "U+20AC,"  # euro sign
    "U+2190-21FF"  # arrows, if the font has them
)
FEATURES = ["kern", "liga", "clig", "calt", "locl", "case", "tnum", "pnum"]

NOTICE = f"""{FAMILY} is a modified version of Libron v0.30 by Nico Verbruggen
(https://github.com/nicoverbruggen/libron), itself based on Readerly and Newsreader.

Modifications: subset to Latin, Latin-1 Supplement, Latin Extended-A and common
punctuation; family renamed to "{FAMILY}" as required by the Reserved Font Name
"Libron". Generated by scripts/fonts.py in https://github.com/djolex999/djmarkovic.com.

Licensed under the SIL Open Font License 1.1, see OFL.txt. Original copyright
notices are in COPYRIGHT.txt.
"""


def rename(font: TTFont, style: str) -> None:
    names = font["name"]
    full = f"{FAMILY} {style}" if style != "Regular" else FAMILY
    ps = f"{PS_FAMILY}-{style}"
    replacements = {
        1: FAMILY,
        2: style,
        3: f"0.30;{ps}",
        4: full,
        6: ps,
        16: FAMILY,
        17: style,
    }
    names.names = [n for n in names.names if n.nameID not in (16, 17, 18, 21, 22)]
    for name_id, value in replacements.items():
        names.setName(value, name_id, 3, 1, 0x409)
        names.setName(value, name_id, 1, 0, 0)


def build(style: str) -> Path:
    src = SOURCE / f"Libron-{style}.woff2"
    if not src.exists():
        raise FileNotFoundError(f"missing source font: {src}")

    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = FEATURES
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.notdef_outline = True

    font = TTFont(src)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=subset.parse_unicodes(UNICODES))
    subsetter.subset(font)
    rename(font, style)

    out = OUT / f"{PS_FAMILY}-{style}.woff2"
    font.flavor = "woff2"
    font.save(out)
    return out


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for style in STYLES:
        out = build(style)
        before = (SOURCE / f"Libron-{style}.woff2").stat().st_size
        print(f"fonts: {out.relative_to(ROOT)}  {before / 1024:.1f} KB -> {out.stat().st_size / 1024:.1f} KB")
    shutil.copy(SOURCE / "OFL.txt", OUT / "OFL.txt")
    shutil.copy(SOURCE / "COPYRIGHT.txt", OUT / "COPYRIGHT.txt")
    (OUT / "NOTICE.txt").write_text(NOTICE, encoding="utf-8")


if __name__ == "__main__":
    main()
